# EDA Notebook

## 1. Importar librerías necesarias
Importar pandas, numpy, matplotlib y seaborn para el análisis y visualización de datos.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from pathlib import Path
from ..src.config import RAW_PATH, OUT_PATH
from ..src.io import load_csv

ROOT = Path().resolve().parent

RAW_PATH = ROOT / "data" / "raw"
EP_RAW = "EP.txt"
IN_RAW = "IN.txt"
MU_RAW = "MU.txt"
MW_RAW = "MW.txt"
CSV_RAWS = []

input_names = [EP_RAW, IN_RAW, MU_RAW, MW_RAW]
for name in input_names:
    data_rows = []

    with open(RAW_PATH / name, "r") as file:
        for registry in file:
            # Separar por comas cada línea
            parts = registry.split("\t")

            # Los primeros 6 elementos son los metadatos
            metadata = parts[:6]

            # El resto de la línea es la señal neuronal
            signal = parts[6].split(",")

            # Creamos un diccionario limpio por cada fila
            row = {
                "id": metadata[0],
                "event": metadata[1],
                "device": metadata[2],
                "channel": metadata[3],
                "code": metadata[4],
                "size": metadata[5],
                "signal": signal,  # La señal se guarda como una lista
            }
            
            data_rows.append(row)

    df = pd.DataFrame(data_rows)
    output_name = name.replace('.txt','.csv')
    
    df.to_csv(RAW_PATH / output_name, index=False)
    
    CSV_RAWS.append(output_name)

## 2. Cargar el archivo CSV
Solicitar al usuario la ruta del archivo .csv y cargarlo en un DataFrame de pandas.

In [ ]:
# Change this path to point to your data file
file_path = '../data/raw/BCICIV_2a_all_patients.csv'
df = pd.read_csv(file_path)

## 3. Visualizar las primeras filas del dataset
Mostrar las primeras filas del DataFrame usando head() para obtener una vista general de los datos.

In [31]:
df.head()

,patient,time,label,epoch,EEG-Fz,EEG-0,EEG-1,EEG-2,EEG-3,EEG-4,...,EEG-8,EEG-9,EEG-10,EEG-11,EEG-12,EEG-13,EEG-14,EEG-Pz,EEG-15,EEG-16
0,1,-0.100,tongue,8,-1.681412,2.245496,-0.158350,1.163765,-1.523659,-0.575267,...,0.758116,3.441785,0.305517,1.137473,-1.275763,-2.898359,0.656704,-2.010063,-1.613804,-1.942455
1,1,-0.096,tongue,8,0.420417,0.587559,1.650510,0.970672,1.505904,0.891796,...,1.541586,-0.071620,0.258909,-1.448198,0.142472,-1.968405,-1.733655,-2.935578,-3.125256,-4.674610
2,1,-0.092,tongue,8,0.551365,1.499758,0.121302,2.859433,2.613414,4.636026,...,2.649097,-2.137938,-1.612096,-1.610218,-0.410173,-0.274957,-4.776535,-5.099551,-2.798995,-5.862021
3,1,-0.088,tongue,8,3.054916,-1.807238,1.843603,2.286812,5.995872,6.651295,...,6.031554,-5.249621,-2.672998,-3.452370,0.189081,1.593829,-6.081577,-5.476860,-2.932163,-6.874095
4,1,-0.084,tongue,8,2.506710,-2.453101,0.221178,0.127278,4.519931,6.249573,...,7.827097,-5.309546,-2.488783,-3.707608,1.447515,4.268278,-4.383690,-4.218426,-1.331932,-5.322692

## 4. Explorar información general del dataset
Utilizar info() y shape para mostrar información sobre el número de filas, columnas y tipos de datos.

In [32]:
df.info()
print(f"Número de filas: {df.shape[0]}")
print(f"Número de columnas: {df.shape[1]}")

<class 'pandas.DataFrame'>
RangeIndex: 492048 entries, 0 to 492047
Data columns (total 26 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   patient  492048 non-null  int64
 1   time     492048 non-null  float64
 2   label    492048 non-null  str
 3   epoch    492048 non-null  int64
 4   EEG-Fz   492048 non-null  float64
 5   EEG-0    492048 non-null  float64
 6   EEG-1    492048 non-null  float64
 7   EEG-2    492048 non-null  float64
 8   EEG-3    492048 non-null  float64
 9   EEG-4    492048 non-null  float64
 10  EEG-5    492048 non-null  float64
 11  EEG-C3   492048 non-null  float64
 12  EEG-6    492048 non-null  float64
 13  EEG-Cz   492048 non-null  float64
 14  EEG-7    492048 non-null  float64
 15  EEG-C4   492048 non-null  float64
 16  EEG-8    492048 non-null  float64
 17  EEG-9    492048 non-null  float64
 18  EEG-10   492048 non-null  float64
 19  EEG-11   492048 non-null  float64
 20  EEG-12   492048 non-null  float64
 21  EEG-13   492048 non-null  float64
 22  EEG-14   492048 non-null  float64
 23  EEG-Pz   492048 non-null  float64
 24  EEG-15   492048 non-null  float64
 25  EEG-16   492048 non-null  float64
dtypes: float64(23), int64(2), str(1)
memory usage: 97.6 MB
Número de filas: 492048
Número de columnas: 26

## 5. Describir variables numéricas y categóricas
Usar describe() para variables numéricas y value_counts() para variables categóricas.

In [33]:
# Numerical variables
df.describe()

# Categorical values (Example for a columnn)
# df['category_column'].value_counts()

,patient,time,epoch,EEG-Fz,EEG-0,EEG-1,EEG-2,EEG-3,EEG-4,EEG-5,...,EEG-8,EEG-9,EEG-10,EEG-11,EEG-12,EEG-13,EEG-14,EEG-Pz,EEG-15,EEG-16
count,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,...,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000,492048.000000
mean,5.058824,0.300000,312.133578,-0.811991,-0.399268,-0.669511,-0.908202,-0.607526,-0.325437,0.161790,...,0.204116,0.503087,0.305026,0.198725,0.255002,0.403190,0.741585,0.656315,0.618452,0.770249
std,2.645100,0.232092,176.757760,7.345682,5.758001,5.182636,5.864248,5.159808,5.475433,6.364779,...,6.205865,5.213024,3.651272,3.858260,3.715157,5.382023,5.700428,5.596708,5.853360,8.009687
min,1.000000,-0.100000,4.000000,-83.147212,-41.675317,-33.485423,-47.021740,-38.127339,-46.884049,-48.302710,...,-59.941901,-44.244171,-26.766605,-34.876342,-34.383536,-80.331997,-44.953972,-45.883926,-50.665326,-63.052646
25%,3.000000,0.100000,159.750000,-4.968283,-3.791030,-3.677560,-4.254897,-3.664436,-3.591620,-3.696852,...,-3.477809,-2.334381,-1.782227,-2.022270,-1.876298,-2.423160,-2.612049,-2.568257,-2.790032,-3.918116
50%,5.000000,0.300000,312.000000,-0.657985,-0.315676,-0.554353,-0.732763,-0.513890,-0.295103,0.155490,...,0.172776,0.518842,0.288530,0.194630,0.223781,0.400869,0.622900,0.544408,0.516750,0.615729
75%,7.000000,0.500000,465.000000,3.458858,3.057477,2.433318,2.581403,2.498685,2.943858,4.040869,...,3.859897,3.433846,2.412297,2.474890,2.396761,3.280874,4.007513,3.831749,3.953051,5.326128
max,9.000000,0.700000,656.000000,56.453337,51.751069,39.955918,40.397420,32.779037,38.145863,68.064016,...,67.502066,45.002544,40.933676,24.452903,25.866699,40.688767,42.318192,41.931835,45.042494,67.761316

## 6. Visualizar valores nulos y duplicados
Identificar y visualizar la cantidad de valores nulos y filas duplicadas en el dataset.

In [34]:
# Null values
print('Null values:\n', df.isnull().sum())

# Duplicated rows
print('\nDuplicated rows: ', df.duplicated().sum())

Null values:
 patient    0
time       0
label      0
epoch      0
EEG-Fz     0
EEG-0      0
EEG-1      0
EEG-2      0
EEG-3      0
EEG-4      0
EEG-5      0
EEG-C3     0
EEG-6      0
EEG-Cz     0
EEG-7      0
EEG-C4     0
EEG-8      0
EEG-9      0
EEG-10     0
EEG-11     0
EEG-12     0
EEG-13     0
EEG-14     0
EEG-Pz     0
EEG-15     0
EEG-16     0
dtype: int64

Duplicated rows:  0

## 7. Análisis univariado de variables numéricas
Realizar histogramas y boxplots para analizar la distribución de las variables numéricas.

In [35]:
# Histogram for a numerical variable
# df['numeric_column'].hist()
# plt.show()

# Boxplot
# df.boxplot(column='numeric_column')
# plt.show()

## 8. Análisis univariado de variables categóricas
Realizar gráficos de barras para analizar la frecuencia de las variables categóricas.

In [36]:
# Bar plot for a categorical variable
# df['categorical_column'].value_counts().plot(kind='bar')
# plt.show()

## 9. Análisis bivariado entre variables
Explorar relaciones entre variables numéricas y categóricas mediante scatterplots y tablas cruzadas.

In [37]:
# Scatterplot
# plt.scatter(df['numeric_column_x'], df['numeric_column_y'])
# plt.show()

# Crosstab for two categorical variables   
# pd.crosstab(df['categorical_column1'], df['categorical_column2'])

## 10. Visualización de correlaciones
Calcular y visualizar la matriz de correlación entre variables numéricas usando un heatmap.

In [38]:
# Correlation matrix
corr = df.corr()
sns.heatmap(corr, annot=True)
plt.show()

ValueError: could not convert string to float: 'tongue'